"""Report generator helpers and commands."""
import sys
import json
from datetime import datetime
from pathlib import Path
from typing import Optional

import click
from rich.panel import Panel

from vexa.reports.generator import get_report_generator, ReportMetadata
from vexa_cli.ui.output import print_banner, print_success, print_error, print_info, console

def _generate_report(result, format: str, output_dir: Path, scan_target: Path) -> Path:
    """Generate report and return path."""
    generator = get_report_generator()
    
    metadata = ReportMetadata(
        title="Vexa Security Scan Report",
        scan_target=str(scan_target.resolve()),
        scan_duration=result.duration_seconds,
        job_id=result.job_id,
    )
    
    return generator.generate(result, format, output_dir, metadata)

@click.command()
@click.argument("path", type=click.Path(exists=True, path_type=Path))
@click.option(
    "--format", "-f",
    type=click.Choice(["html", "json", "sarif", "markdown", "all"]),
    multiple=True,
    default=["all"],
    help="Output report format (default: all)"
)
@click.option(
    "--output", "-o",
    type=click.Path(path_type=Path),
    default=None,
    help="Output directory for reports (default: 'vexa_reports' in the scanned directory)"
)
def report(path: Path, format: tuple, output: Optional[Path]):
    """
    Generate report from previous scan results.
    
    PATH: Path to a previously generated Vexa JSON report file.
    
    Example:
        vexa report ./vexa_scan_reports/scan_1/report.json --format html
    """
    print_banner()
    
    start_time = datetime.now()
    console.print(f"\\n[bold white]📝 Report Generation Initiated:[/bold white] [bright_cyan]{start_time.strftime('%Y-%m-%d %H:%M:%S')}[/bright_cyan]")
    console.print("─" * 50)
    
    if path.is_dir() or not path.name.endswith(".json"):
        print_error("PATH must be a .json file generated by a previous Vexa scan.")
        sys.exit(1)
        
    formats_to_gen = list(format)
    if "all" in formats_to_gen:
        formats_to_gen = ["html", "json", "sarif", "markdown"]
        
    if output:
        base_output_dir = output
    else:
        base_output_dir = path.parent
        
    base_output_dir.mkdir(parents=True, exist_ok=True)
    
    # Show configuration
    conf_content = (
        f"[bold sky_blue1]Input JSON:[/bold sky_blue1] [blue]{path.resolve()}[/blue]\\n"
        f"[bold sky_blue1]Output Dir:[/bold sky_blue1] [blue]{base_output_dir.resolve()}[/blue]\\n"
        f"[bold sky_blue1]Formats:[/bold sky_blue1]    [white]{', '.join([f.upper() for f in formats_to_gen])}[/white]\\n"
    )
    console.print(Panel(conf_content, title="[bold white]Report Configuration[/bold white]", border_style="bright_cyan", expand=False))
    console.print()
    
    try:
        from vexa.common.models import ScanResult
        
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        print_info(f"Loaded JSON payload from '{path.name}'...")
        
        # Validating the JSON string data against the Pydantic ScanResult model
        result = ScanResult.model_validate(data)
        print_success(f"Successfully unpacked {result.total_findings} findings.")
        
    except Exception as e:
        print_error(f"Failed to load or parse JSON scan result: {e}")
        sys.exit(1)
        
    console.print(f"\\n[bold white]📝 Generated Reports[/bold white]")
    report_files = []
    
    for fmt in formats_to_gen:
        try:
            report_path = _generate_report(result, fmt, base_output_dir, path)
            report_files.append((fmt.upper(), report_path.name))
        except Exception as e:
            print_error(f"  • {fmt.upper():<8} : Failed ({e})")
            
    for fmt_name, filename in report_files:
        console.print(f"  • [bold sky_blue1]{fmt_name:<10}:[/bold sky_blue1] [white]{filename}[/white]")
            
    console.print("─" * 50)
    console.print(f"[bold white]🏁 Finished:[/bold white] [bright_cyan]{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}[/bright_cyan]\\n")
