"""
Markdown Report Generator for Vexa.

SS-006: Documentation-friendly Markdown report output.
"""

from pathlib import Path
from typing import List, Optional

from vexa.reports.generator import BaseReportGenerator, ReportGenerator, ReportMetadata
from vexa.scanners.base import Finding
from vexa.scanners.engine import ScanResult
from vexa.common.logging import get_logger


logger = get_logger(__name__)


class MarkdownReportGenerator(BaseReportGenerator):
    """
    SS-006: Markdown report generator for documentation.

    Produces GitHub-flavored Markdown output suitable for:
    - README files
    - Wiki pages
    - Documentation sites
    - Pull request comments
    """

    format_name = "markdown"
    file_extension = ".md"

    # Severity emoji mapping
    SEVERITY_EMOJI = {
        "critical": "🔴",
        "high": "🟠",
        "medium": "🟡",
        "low": "🔵",
        "info": "⚪",
    }

    def generate(
        self,
        result: ScanResult,
        output_path: Path,
        metadata: Optional[ReportMetadata] = None,
    ) -> Path:
        """Generate Markdown report."""
        output_path = self._prepare_output_path(output_path)
        metadata = metadata or ReportMetadata()

        content = self._render_report(result, metadata)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        return output_path

    def _render_report(self, result: ScanResult, metadata: ReportMetadata) -> str:
        """Render the Markdown report."""
        severity_counts = self._get_severity_counts(result.findings)
        scanner_counts = self._get_scanner_counts(result.findings)

        lines = [
            f"# 🔒 {metadata.title}",
            "",
            f"> Generated: {metadata.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"> Duration: {result.duration_seconds:.2f}s",
            f"> Job ID: {metadata.job_id}",
            "",
            "---",
            "",
            "## 📊 Summary",
            "",
            f"**Total Findings:** {result.total_findings}",
            "",
            "### By Severity",
            "",
            "| Severity | Count |",
            "|----------|-------|",
        ]

        for severity in ["critical", "high", "medium", "low", "info"]:
            emoji = self.SEVERITY_EMOJI.get(severity, "")
            count = severity_counts.get(severity, 0)
            lines.append(f"| {emoji} {severity.capitalize()} | {count} |")

        lines.extend(
            [
                "",
                "### By Scanner",
                "",
                "| Scanner | Findings |",
                "|---------|----------|",
            ]
        )

        for scanner, count in sorted(scanner_counts.items()):
            lines.append(f"| {scanner} | {count} |")

        lines.extend(
            [
                "",
                "---",
                "",
                "## 🔍 Findings",
                "",
            ]
        )

        if not result.findings:
            lines.append("✅ No security issues detected!")
        else:
            lines.extend(self._render_findings(result.findings))

        lines.extend(
            [
                "",
                "---",
                "",
                f"*Generated by Vexa v{metadata.tool_version}*",
            ]
        )

        return "\n".join(lines)

    def _render_findings(self, findings: List[Finding]) -> List[str]:
        """Render findings as professional Markdown with GitHub alerts."""
        if not findings:
            return ["## ✅ No security issues detected."]

        lines = ["## 🔍 Detailed Findings", ""]

        # Severity to icon mapping
        icons = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🔵",
            "info": "⚪",
        }

        # Sort findings by severity
        severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
        sorted_findings = sorted(
            findings,
            key=lambda f: severity_order.get(
                f.severity.value if hasattr(f.severity, "value") else f.severity, 5
            ),
        )

        # Line 151 onwards
        for finding in sorted_findings:
            severity = (
                finding.severity.value
                if hasattr(finding.severity, "value")
                else finding.severity
            ).lower()
            icon = icons.get(severity, "🔍")

            lines.extend(
                [
                    f"### {icon} {finding.title}",
                    "",
                    f"- **Severity:** {severity.upper()}",
                    f"- **Location:** `{finding.file_path}:{finding.line_start}`",
                    f"- **Scanner:** `{finding.scanner.upper()}`",
                ]
            )

            if getattr(finding, "is_false_positive", False):
                lines.extend(
                    [
                        "> [!CAUTION]",
                        f"> **AI-DETECTED FALSE POSITIVE** (Confidence: {finding.false_positive_confidence * 100:.0f}%)",
                        f"> {getattr(finding, 'fp_explanation', 'AI analysis suggests this finding is a false positive based on the context.')}",
                        "",
                    ]
                )

            # ALWAYS show framework mappings if they exist
            frameworks = []
            if finding.cwe_ids:
                frameworks.append(f"**CWE:** {', '.join(finding.cwe_ids)}")
            if finding.owasp_category:
                frameworks.append(f"**OWASP:** {finding.owasp_category}")
            if finding.mitre_attack_id:
                frameworks.append(f"**MITRE ATT&CK:** {finding.mitre_attack_id}")
            if finding.nist_controls:
                frameworks.append(f"**NIST:** {', '.join(finding.nist_controls)}")

            if frameworks:
                lines.extend([*[f"- {f}" for f in frameworks]])

            lines.extend(
                [
                    "",
                    f"> {finding.description}",
                    "",
                ]
            )

            if finding.code_snippet:
                lines.extend(
                    [
                        "#### 📄 Source Code (Before Fix)",
                        "```",
                        f"{getattr(finding, 'code_snippet_before', finding.code_snippet)}",
                        "```",
                        "",
                    ]
                )

                lines.extend(
                    [
                        "#### 📄 Source Code (Location)",
                        "```",
                        f"{finding.code_snippet}",
                        "```",
                        "",
                    ]
                )

            # AI Enhancements
            if (
                hasattr(finding, "detailed_description")
                and finding.detailed_description
            ):
                lines.extend(
                    [
                        "#### 🤖 AI Security Analysis",
                        "",
                        f"{finding.detailed_description}",
                        "",
                    ]
                )

                if finding.attack_scenario:
                    lines.extend(
                        [
                            "> [!WARNING]",
                            "> **Attack Scenario**",
                            f"> {finding.attack_scenario}",
                            "",
                        ]
                    )

                if finding.business_impact:
                    lines.extend(
                        [
                            "> [!IMPORTANT]",
                            "> **Business Impact**",
                            f"> {finding.business_impact}",
                            "",
                        ]
                    )

                if getattr(finding, "exploitability", "unknown") != "unknown":
                    lines.append(
                        f"**Exploitability:** `{finding.exploitability.upper()}`"
                    )
                    lines.append("")

                # Remediation
                if getattr(finding, "remediation_code", ""):
                    lines.extend(
                        [
                            "#### ✅ Suggested Remediation",
                            "> [!TIP]",
                            "> Apply the following fix to address this vulnerability.",
                            "",
                            "```",
                            f"{finding.remediation_code}",
                            "```",
                            "",
                        ]
                    )

                if getattr(finding, "implementation_steps", []):
                    lines.append("**Implementation Steps:**")
                    for step in finding.implementation_steps:
                        lines.append(f"1. {step}")
                    lines.append("")

                # Cloud Recommendations
                gcp_rec = getattr(finding, "google_cloud_recommendation", "")
                if gcp_rec:
                    lines.extend(
                        [
                            "#### ☁️ Google Cloud Recommendation",
                            f"{gcp_rec}",
                            "",
                        ]
                    )

                aws_rec = getattr(finding, "aws_recommendation", "")
                if aws_rec:
                    pillar = getattr(finding, "aws_well_architected_pillar", "")
                    pillar_text = f" (Pillar: {pillar})" if pillar else ""
                    lines.extend(
                        [
                            f"#### ☁️ AWS Recommendation{pillar_text}",
                            f"{aws_rec}",
                            "",
                        ]
                    )

                # Test Cases

                # Links
                links = getattr(finding, "google_cloud_doc_links", []) or getattr(
                    finding, "aws_doc_links", []
                )
                if links:
                    lines.extend(["#### 📚 Documentation & References", ""])
                    for link in links:
                        lines.append(f"- [{link}]({link})")
                    lines.append("")

                # Test Cases
                test_cases = getattr(finding, "test_cases", [])
                if test_cases:
                    lines.extend(["#### 🧪 Verification Test Cases", ""])
                    for test in test_cases:
                        lines.append(f"- [ ] {test}")
                    lines.append("")

            lines.append("---")
            lines.append("")

        return lines


# Register with ReportGenerator
ReportGenerator.register(MarkdownReportGenerator)
